### ISSUE TITLE
detectlanguage api suspended immediately

### ISSUE THREAD

**Issue by fribse** [Steven-Gassert/MMM-PoemOfTheDay#6] opened 2020-03-11 05:59 UTC
Hi there

I've set up the poem module in my magicmirror yesterday, I've set the config to:

```
    {
      module: "MMM-PoemOfTheDay",
      position: "lower_third",
      classes: "evening_schedule",
      config: {
        textLimit: 1000,
        lineLimit: 10,
        detectLanguageApiKey: "VERYSECRET",
        languageSet: ["da"],
        updateInterval: 120000
      }
    },
```

But less than an hour after activation I've gotten a mail about the api being suspended as I've used all the free lookups. I got it at 2 am again (a new day with 1000 free lookups).
So it seems that it goes completely bonkers and uses 1000 lookups every time it changes the poem.

**Comment by fribse** [comment] 2020-08-09 15:36
Still an issue, module is now gone :-(

**Comment by Steven-Gassert** [comment] 2020-08-10 19:03
Hi @fribse , thanks for checking out my Module! Unfortunately the root cause of this issue lies in the fact that the database we use to fetch poems (https://www.poemist.com/) does not have many (if any) Danish poems. Since you have your module config to only display poems in Danish, and the api we use does not allow us to first filter by language, we must constantly fetch poems until we find one for the language config you've selected

A good fix for this issue would be narrowing down the language codes we accept to only those contained in the poemist DB.

**Comment by Steven-Gassert** [comment] 2020-08-10 19:07
Thanks again for the feedback @fribse, I've opened an issue here to track this work: https://github.com/Steven-Gassert/MMM-PoemOfTheDay/issues/8

**Closed as completed by Steven-Gassert** 2020-08-10 19:07 UTC
